// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inlkrzvknbcaaefwmiux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubGtyenZrbmJjYWFlZndtaXV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTk3MzgsImV4cCI6MjA2NDAzNTczOH0._B5-yq6QXTQEXq0vm_ld3uDuvkN3G3zllljqwoMY-a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);